import { MoreType } from "components/Section/Works/WorkItem";

export const WorkType: { [key: string]: string } = {
  Everything: "*",
  Web: "web",
  Mobile: "mobile",
  Own: "own",
};

export const CompanyType: { [key: string]: string } = {
  Everything: "*",
  "GMO-Z.com Runsystem": "gmo",
  "TQ Design": "tqdesign",
  "BSD SOLUTION": "bsd",
  "FPT Shop": "fptshop",
};

export const cvConfig = {
  title: "Nguyen Hoang Duy",
  description:
    "Front-end Engineer with 7+ years of experience specializing in building scalable web applications using Vue.js, Nuxt.js and React, Next.js. Proven track record in leading development teams, optimizing performance for high-traffic Fintech platforms, and implementing CI/CD workflows.",
  name: "Nguyen Hoang Duy",
  about: `Front-end Engineer with 7+ years of experience specializing in building scalable web applications using Vue.js, Nuxt.js and React, Next.js. Proven track record in leading development teams, optimizing performance for high-traffic Fintech platforms, and implementing CI/CD workflows. Passionate about clean code, UI/UX architecture, and mentoring junior developers.`,
  mainJob: ["Front-end Engineer", "7+ years experience in Vue.js, Nuxt.js, React, Next.js"],
  cvDownloadLink: "/Nguyen-Hoang-Duy.pdf",
  skills: [
    {
      name: "JavaScript (ES6+) / TypeScript",
      value: 95,
      bgColor: "#0866a9",
    },
    {
      name: "Vue.js (Vue 2/3) / Nuxt.js",
      value: 95,
      bgColor: "#6aab80",
    },
    {
      name: "React / Next.js",
      value: 85,
      bgColor: "#60dafa",
    },
    {
      name: "HTML5 / CSS3 / SCSS",
      value: 95,
      bgColor: "#e96228",
    },
    {
      name: "Tailwind CSS / MUI / Bootstrap",
      value: 90,
      bgColor: "#9c27b0",
    },
    {
      name: "Testing (Jest, Appium, CodeceptJS)",
      value: 80,
      bgColor: "#ff9800",
    },
  ],
  facts: [
    {
      icon: "icon-fire",
      name: "Years of experience",
      count: 7,
    },
    {
      icon: "icon-badge",
      name: "Awards won",
      count: 1,
    },
    {
      icon: "icon-people",
      name: "Major projects",
      count: 11,
    },
  ],
  awards: [
    {
      year: "2022",
      title: "Employee of the year award (Front end)",
      company: "GMO Z.com Runsystem",
    },
  ],
  menu: [
    {
      label: "Home",
      href: "home",
      className: "icon-home",
    },
    {
      label: "About",
      href: "about",
      className: "icon-user-following",
    },
    {
      label: "Services",
      href: "services",
      className: "icon-briefcase",
    },
    {
      label: "Experience",
      href: "experience",
      className: "icon-graduation",
    },
    {
      label: "Works",
      href: "works",
      className: "icon-layers",
    },
    {
      label: "Blog",
      href: "blog",
      className: "icon-note",
      disabled: true,
    },
    {
      label: "Contact",
      href: "contact",
      className: "icon-bubbles",
    },
  ],
  services: [
    {
      className: "text-light",
      imgSrc: "/images/service-1.svg",
      bgColor: "#6aab80",
      name: "Web Development",
      description:
        "I'm currently working with VueJS. Besides, I can also code with ReactJS. The applications I make are high performance and have beautiful effects. NuxtJS/ NextJs is my favorite framework.",
    },
    {
      className: "text-dark",
      imgSrc: "/images/service-2.svg",
      bgColor: "#F9D74C",
      name: "Web Development",
      description: "In addition, I am also good at converting designs (Figma, Photoshop) to websites using html/css/js",
    },
    {
      className: "text-light",
      imgSrc: "/images/service-3.svg",
      bgColor: "#F97B8B",
      name: "Blogger & SEOer",
      description: "In my free time, I write blog posts to share my experiences.",
    },
  ],
  experience: {
    education: [
      {
        time: "Sep 2013 - Nov 2017",
        title: "Ho Chi Minh University of Science - Vietnam National",
        description: "Software Engineer",
      },
    ],
    work: [
      {
        time: "June 2019 - Now",
        title: "Front-end Developer",
        company: "GMO-Z.com Runsystem",
        description: `Do projects from Japanese customers. Typical customers: NHK Television, Chintai, Fintech. Develop web applications using VueJS/NuxtJS, ReactJS/NextJS, HTML5/CSS3, JavaScript/TypeScript, jQuery, Bootstrap, TailwindCSS, SCSS. Lead development teams, optimize performance for high-traffic Fintech platforms, and implement CI/CD workflows.`,
      },
      {
        time: "June 2017 - April 2019",
        title: "Front-end & Back-end Developer",
        company: "TQ Design",
        description: `Maintained and developed responsive websites using HTML5, CSS3, Bootstrap 4, and jQuery. Supported backend development with C# (ASP.NET) and CMS management. Converted PSD designs into high-quality HTML/CSS templates ensuring pixel-perfect accuracy.`,
      },
      {
        time: "Jan 2017 - May 2017",
        title: "Back-end Developer (ASP.Net)",
        company: "BSD SOLUTION",
        description: `Developed product sugar cane house manager for TTC Group`,
      },
      {
        time: "March 2016 - Jan 2017",
        title: "Back-end Developer (ASP.Net)",
        company: "FPT Shop",
        description: `Developed web MVC webform, use database SQL Server for back-end. Utilized Bootstrap, HTML5/CSS3, jQuery library, technical web responsive.`,
      },
    ],
  },
  works: [
    {
      type: [WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "Paydar - Fintech Platform",
      term: "TypeScript, SCSS, Tailwind CSS, Axios, NestJS",
      description:
        "Web platform development for Fintech. Engineered complex features and UI components using TypeScript. Implemented responsive designs using SCSS and Tailwind CSS.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/chikipay.png",
      href: "https://paydar.com/",
    },
    {
      type: [WorkType.Mobile, WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "Chikiipay - E-wallet",
      term: "Vue 3, TypeScript, Appium, CodeceptJS, Tailwind CSS, GitLab CI/CD",
      description:
        "A payment solution application developed for Japanese market. Role: sub-lead (team 5 members). Automated front-end testing using Appium and CodeceptJS.",
      moreIcon: MoreType.Options,
      thumbnail: "/images/works/chikipay.png",
      href: "https://web.chikipay-kyousou.jp/",
    },
    {
      type: [WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "Metauranai - Fortune Telling Platform",
      term: "Next.js, React, JavaScript, Firebase, PlayCanvas, AI",
      description:
        "A web app for fortune-telling content and user interaction. Role: Leader (team 4 members). Built features using React (Next.js) and integrated with backend APIs.",
      moreIcon: MoreType.Options,
      thumbnail: "/images/works/metaurai.png",
      href: "#",
    },
    {
      type: [WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "RKKCS - Management System",
      term: "Vue 2, Nuxt.js, JavaScript, SCSS, Axios, Jest",
      description:
        "A management platform for internal use by a Japanese client. Developed and maintained front-end features using Vue.js and Nuxt.js. Wrote unit tests with Jest following TDD principles.",
      moreIcon: MoreType.Options,
      thumbnail: "/images/works/chintai.png",
      href: "#",
    },
    {
      type: [WorkType.Mobile, WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "NHK School CMS & NHK Archives",
      term: "Vue 2, Nuxt.js, Tailwind CSS, Vuex, GitLab CI/CD",
      description:
        "Content management systems for NHK's educational platforms. Implemented admin dashboards and dynamic content modules. Collaborated with UI/UX designers to ensure pixel-perfect interfaces.",
      moreIcon: MoreType.Options,
      thumbnail: "/images/works/nhk.jpg",
      href: "https://www.nhk.or.jp/school",
    },
    {
      type: [WorkType.Mobile, WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "Drill - Online Exam Platform",
      term: "Vue 3, TypeScript, RESTful API, SCSS",
      description:
        "An online examination system designed for Japanese students. Built interactive quiz and test-taking interfaces using Vue 3. Implemented features for real-time feedback and scoring.",
      moreIcon: MoreType.Options,
      thumbnail: "/images/works/drill.png",
      href: "https://digistudy.sing.jp/login",
    },
    {
      type: [WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "RemoteWork Cloud",
      term: "Nuxt 3, Vue 3, Tailwind CSS, RESTful API",
      description:
        "A cloud-based remote work management platform. Developed UI features using Nuxt 3 and TailwindCSS. Optimized components for performance and mobile responsiveness.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/chintai.png",
      href: "https://remotework-cloud.com/",
    },
    {
      type: [WorkType.Web],
      company: "GMO-Z.com Runsystem",
      title: "ChintaiDX - Hotel Management",
      term: "Vue 2, JavaScript, GraphQL, GitLab CI/CD",
      description:
        "A hotel management platform for real estate services. Built responsive front-end pages using Vue.js. Integrated interactive features with real-time data updates.",
      moreIcon: MoreType.Options,
      thumbnail: "/images/works/chintai.png",
      href: "http://admin.chintaidx.com/#/auth/login",
    },
    {
      type: [WorkType.Web],
      company: "TQ Design",
      title: "Thanh Pho Caphe",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, C#",
      description:
        "Responsive website development. Converted PSD designs into high-quality HTML/CSS templates ensuring pixel-perfect accuracy.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/tqdesign.jpg",
      href: "https://thanhphocaphe.com",
    },
    {
      type: [WorkType.Web],
      company: "TQ Design",
      title: "Dragon Village",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, C#",
      description:
        "Project about an apartment complex development. Converted PSD designs into high-quality HTML/CSS templates ensuring pixel-perfect accuracy.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/dragonvillage.png",
      href: "https://dragonvillage.com.vn/",
    },
    {
      type: [WorkType.Web],
      company: "TQ Design",
      title: "TQ Design",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, C#",
      description: "Maintained and developed responsive websites using HTML5, CSS3, Bootstrap 4, and jQuery.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/tqdesign.jpg",
      href: "https://tqdesign.vn",
    },
    {
      type: [WorkType.Web],
      company: "TQ Design",
      title: "The Max",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, C#",
      description: "Responsive website development. Converted PSD designs into high-quality HTML/CSS templates.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/tqdesign.jpg",
      href: "https://themax.vn",
    },
    {
      type: [WorkType.Web],
      company: "TQ Design",
      title: "Kingdom 101",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, C#",
      description: "Responsive website development. Converted PSD designs into high-quality HTML/CSS templates.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/tqdesign.jpg",
      href: "https://kingdom101.tqdesign.vn",
    },
    {
      type: [WorkType.Web],
      company: "TQ Design",
      title: "AKARI City",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, C#",
      description: "Responsive website development. Converted PSD designs into high-quality HTML/CSS templates.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/AKARI-nha.jpg",
      href: "https://akaricity.vn/",
    },
    {
      type: [WorkType.Web],
      company: "BSD SOLUTION",
      title: "Sugar Cane House Manager",
      term: "ASP.NET, C#, SQL Server",
      description:
        "Developed product sugar cane house manager for TTC Group. Back-end development using ASP.NET and SQL Server.",
      moreIcon: MoreType.Options,
      thumbnail: "/images/works/default-placeholder.svg",
      href: "#",
    },
    {
      type: [WorkType.Web],
      company: "FPT Shop",
      title: "Viec Lam FPT Shop",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, SQL Server",
      description:
        "Revamped website, developed new landing page. Utilized Bootstrap, HTML5/CSS3, jQuery library, technical web responsive.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/default-placeholder.svg",
      href: "https://vieclam.fptshop.com.vn",
    },
    {
      type: [WorkType.Web],
      company: "FPT Shop",
      title: "Inside FPT Shop",
      term: "ASP.NET MVC, HTML5/CSS3, jQuery, SQL Server",
      description:
        "Developed web MVC webform, use database SQL Server for back-end. Utilized Bootstrap, HTML5/CSS3, jQuery library, technical web responsive.",
      moreIcon: MoreType.Link,
      thumbnail: "/images/works/default-placeholder.svg",
      href: "https://inside.fptshop.com.vn",
    },
    // {
    //   type: [WorkType.Web],
    //   title: "CloudFlow CRM",
    //   term: "VueJS, TailwindCSS",
    //   description: "Enterprise-level customer relationship management system",
    //   moreIcon: MoreType.Link,
    //   thumbnail: "/images/works/crm-system.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Web],
    //   title: "HealthTrack Pro",
    //   term: "NextJS, GraphQL",
    //   description: "Healthcare management platform for clinics and hospitals",
    //   moreIcon: MoreType.Options,
    //   thumbnail: "/images/works/health-platform.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Mobile],
    //   title: "FitnessPal Mobile",
    //   term: "React Native",
    //   description: "Fitness tracking and workout planning mobile application",
    //   moreIcon: MoreType.Options,
    //   thumbnail: "/images/works/fitness-app.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Web],
    //   title: "EduLearn LMS",
    //   term: "VueJS, NuxtJS",
    //   description: "Modern learning management system for educational institutions",
    //   moreIcon: MoreType.Link,
    //   thumbnail: "/images/works/edu-platform.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Mobile],
    //   title: "SmartHome Controller",
    //   term: "React Native, IoT Integration",
    //   description: "Mobile app for smart home device management",
    //   moreIcon: MoreType.Options,
    //   thumbnail: "/images/works/smart-home.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Web],
    //   title: "TravelPlanner Pro",
    //   term: "NextJS, MongoDB",
    //   description: "Travel itinerary planning and booking platform",
    //   moreIcon: MoreType.Link,
    //   thumbnail: "/images/works/travel-planner.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Mobile],
    //   title: "DeliveryHub",
    //   term: "React Native, Redux",
    //   description: "Food delivery service mobile application",
    //   moreIcon: MoreType.Options,
    //   thumbnail: "/images/works/delivery-app.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Web],
    //   title: "TaskForce Project Management",
    //   term: "VueJS, Firebase",
    //   description: "Collaborative project management tool",
    //   moreIcon: MoreType.Options,
    //   thumbnail: "/images/works/project-management.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Mobile],
    //   title: "CryptoTracker Pro",
    //   term: "React Native, WebSocket",
    //   description: "Real-time cryptocurrency tracking and trading app",
    //   moreIcon: MoreType.Link,
    //   thumbnail: "/images/works/crypto-app.jpg",
    //   href: "#",
    // },
    // {
    //   type: [WorkType.Mobile],
    //   title: "FX｜Securities smartphone app",
    //   term: "Xamarin Forms",
    //   moreIcon: MoreType.Link,
    //   thumbnail: "/images/works/sys-fx.webp",
    //   href: "https://kabu.com/app/sysfx/default.html",
    // },
    // {
    //   type: [WorkType.Mobile],
    //   title: "Bmoji - Custom Emojis by Designers",
    //   term: "Xamarin Forms",
    //   moreIcon: MoreType.Link,
    //   thumbnail: "/images/works/bmoji.webp",
    //   href: "http://www.thebmoji.com",
    // },
    // {
    //   type: [WorkType.Own, WorkType.Web],
    //   title: "AkiraGosho1703 - My blog",
    //   term: "Gatsby",
    //   moreIcon: MoreType.Link,
    //   thumbnail: "/images/works/my-blog.webp",
    //   href: "https://xn--t-lia.vn",
    // },
  ],
};
